### PR TITLE
CMAA2 Optimization

### PR DESCRIPTION
**Pull request by jfouquart**
Hi, it's me again.
I made these modifications to optimize the PixelShader version of CMAA2, I'd like to have your opinion on the idea and also know if it works/or if it an good idea for the Compute version, because I don't have a game to test this. Thanks in advance for your feedback.

PS: I still don't understand why you don't multiply 2.25 at the end of the LongEdgePS function, if you can explain :).
PS2: In my tests, the gain ranged from 10 to 30% depending on the scene.

### CODE REVIEW

**Comment by LordOfLunacy** [comment]
I see you're using a LUT to score the shapes, can you explain your methodology perhaps? I'm guessing this is similar to how SMAA works? Also the 2.25 is done to weight the long edges contribution differently from the contribution from the simple shapes when you accumulate. This is replicated from Intel's original implementation.

**Comment by LordOfLunacy** [comment]
Also something I feel important to mention is I do want to  for better or for worse make sure that the output of the algorithm remain the same as what you would get from the original implementation

**Comment by jfouquart** [comment]
I understand how you feel and I hope the code I use to generate these textures will reassure you.
```HLSL
texture2D ZShapeScores <pooled = true;>{Width = 256; Height = 256; Format = RGBA8;};
sampler2D sZShapeScores {Texture = ZShapeScores;};
texture2D SimpleShapeBlandVal <pooled = true;>{Width = 4096; Height = 256; Format = RGBA8;};
sampler2D sSimpleShapeBlandVal {Texture = SimpleShapeBlandVal;};

void SimpleShapeBlandValPS(float4 position : SV_Position, float2 texcoord : TEXCOORD, out float4 output : SV_TARGET0)
{
	uint2 coord = position.xy;

	float4 edges       = UnpackEdgesFlt(coord.x / 256);
	float4 edgesLeft   = UnpackEdgesFlt((coord.x / 16) % 16);
	float4 edgesRight  = UnpackEdgesFlt(coord.x / 16);
	float4 edgesTop    = UnpackEdgesFlt(coord.y / 16);
	float4 edgesBottom = UnpackEdgesFlt(coord.y % 16);

	output = ComputeSimpleShapeBlendValues(edges, edgesLeft, edgesRight, edgesTop, edgesBottom, true);
}

void ZShapeScoresPS(float4 position : SV_Position, float2 texcoord : TEXCOORD, out float4 output : SV_TARGET0)
{
	uint2 coord = position.xy;

	float4 edges     = UnpackEdgesFlt(coord.x / 16);
	float4 edgesM1P0 = UnpackEdgesFlt(coord.x % 16);
	float4 edgesP1P0 = UnpackEdgesFlt(coord.y / 16);
	float4 edgesP2P0 = UnpackEdgesFlt(coord.y % 16);

	float invertedZScore, normalZScore;

//	uint2 horzPos = uint2(
//		16 * center + left,
//		16 * right + rightTwice);
	DetectZsHorizontal( edges, edgesM1P0, edgesP1P0, edgesP2P0, invertedZScore, normalZScore );
	if( invertedZScore > normalZScore )
	{
		output.x = invertedZScore / 4.0;
		output.y = 1.0;
	}
	else
	{
		output.x = normalZScore / 4.0;
		output.y = 0.0;
	}

//	uint2 vertPos = uint2(
//		16 * center + bottom,
//		16 * top + topTwice);
	DetectZsHorizontal( edges.argb, edgesM1P0.argb, edgesP1P0.argb, edgesP2P0.argb, invertedZScore, normalZScore );
	if( invertedZScore > normalZScore )
	{
		output.z = invertedZScore / 4.0;
		output.w = 1.0;
	}
	else
	{
		output.z = normalZScore / 4.0;
		output.w = 0.0;
	}
}

technique
{
	pass
	{
		VertexShader = PostProcessVS;
		PixelShader = SimpleShapeBlandValPS;
		RenderTarget0 = SimpleShapeBlandVal;
	}
	pass
	{
		VertexShader = PostProcessVS;
		PixelShader = ZShapeScoresPS;
		RenderTarget0 = ZShapeScores;
	}
}
#endif
```
I simply called the original code in a loop and wrote the result to the texture, then saved the texture in a file.

**Comment by jfouquart** [comment]
I've integrated this code directly into the CMAA_2.fx shader  ;)

**Comment by jfouquart** [comment]
I can embed this code as a comment so that anyone can reuse it as needed, if you like.

**Comment by jfouquart** [comment]
In fact, that's what I have on the version on my workstation. ;)

**Comment by LordOfLunacy** [comment]
Doesn't the coord.x /16 in edges right need a %256?

Wait no, edgesRight should be coord.x%16 instead of /16 I think, I know that code doesn't look right though

**Comment by LordOfLunacy** [comment]
Otherwise though I'd say that's a good idea, I would say don't touch the compute shader if you aren't able to test it (if I get the motivation to return to doing this seriously ever I might add it there) and yes, the corrected code for how the LUTs get generated should be a comment. (Also blandvalues.png instead of blendvalues.png, minor thing but would be nice to not have the typo in the texture name

**Comment by jfouquart** [comment]
Oupsi you're right, I modified the algorithm to make it more readable but I didn't regenerate the texture with it. I'll try with the correction to see if there's a change in the regenerated texture.

**Comment by LordOfLunacy** [comment]
Thank you so much for your contributions, they're very well done. I did have one more idea however, the LUT for the simple blend values is quite large, would there be any way to leverage symmetry to make the LUT smaller which would help further increase performance? If not I'm happy to merge these changes now though

**Comment by jfouquart** [comment]
Thanks to you, I spent a long time looking for an anti-aliasing shader that didn't blur fonts. I had read the doc and the CMAA2 shader, I had started to implement it for DX9 but I never managed to get anything satisfactory. Then I came across your truly impressive implementation and thought, rather than do something on my own, I might as well take part in it. Congratulations again.
As for the symmetry, I'm going to have a look, 4MB of LUT, I think that's pretty big too, for the moment I don't have any ideas, but we'll see.
I've also got another question: does the ApplyPS pixelshader really need blend operations?

**Comment by LordOfLunacy** [comment]
The ApplyPS doesn't need blend operations, they are just faster than writing to every pixel

**Comment by LordOfLunacy** [comment]
But yeah CMAA 2 being scatter rather than gather complicated things for sure when it comes to dx9. And even ReShade in general for a while, before it supported atomic texture operations.

**Comment by jfouquart** [comment]
Will DX9 support atomic operations on textures ?

**Comment by LordOfLunacy** [comment]
No, those require compute shaders in ReShade to my knowledge, and their usefulness is limited in pixel shaders anyways

**Comment by jfouquart** [comment]
that's what I was afraid of :(

**Comment by jfouquart** [comment]
Sorry, but at the moment I have no idea how to reduce the size of the “SimpleBlend” LUT. However, I've regenerated the textures and added a “sharp” version for the “SimpleBlend”.

**Pull request merged**
