### PR TITLE
Update CMAA_2.fx

### PR DESCRIPTION
**Pull request by jfouquart**
Since my last commit, I've found a few bugs in the “LongEdge” gradients.
Before:
before
After:
after

### CODE REVIEW

**Comment by LordOfLunacy** [comment]
I noticed you changed the ProccessedCandidates to RGBA8, from RGBA16f, this could cause unintended quantization of edges as more than 1 edge could write to a pixel

**Comment by jfouquart** [comment]
The RGBA16F is used by the compute shader, because I only have DX9 game to test sorry. Or I  misunderstood something 🤔

**Comment by LordOfLunacy** [comment]
The blend operations are used to accumulate in dx9, so this applies there as well. It's not super common so you might not have noticed it, but it does happen.

I'll likely take more of a look at this pr sometime this weekend

**Comment by LordOfLunacy** [comment]
https://github.com/LordOfLunacy/Insane-Shaders/commit/b62b20008d4ca8986521e832dee57f70869d77b0#diff-d9a277b5128f8643c80d7723e51410fdc6d049bfa9358855f6ed586660c6c684L1080

Aha, this is why I can't seem to find the blend operations. This is necessary for the shader to work properly. I didn't notice you had removed these blend operations. If that's what fixed the issue with long edges, that isn't the root cause.

**Comment by jfouquart** [comment]
> [b62b200#diff-d9a277b5128f8643c80d7723e51410fdc6d049bfa9358855f6ed586660c6c684L1080](https://github.com/LordOfLunacy/Insane-Shaders/commit/b62b20008d4ca8986521e832dee57f70869d77b0#diff-d9a277b5128f8643c80d7723e51410fdc6d049bfa9358855f6ed586660c6c684L1080)
> 
> Aha, this is why I can't seem to find the blend operations. This is necessary for the shader to work properly. I didn't notice you had removed these blend operations. If that's what fixed the issue with long edges, that isn't the root cause.

Ha, I remove this code because if I leave it the fix does not work. And effectively, I don't understand why we have to do this. We need to keep the blend operations because we can write multiple time in the same point if I understand correctly your explaination, sorry I missed that, I'll try to reconcile the two then. Thanks for your feedback.

**Comment by jfouquart** [comment]
Why you multiply the output color by 2.25 in the previous version of the "LongEdgePS" function ?

**Comment by jfouquart** [comment]
OMG, I'm so sorry, your code was good from the start, the problem came from the fact that to go from an absolute position in an HLSL texture to a normalized position 0.0-1.0 you have to add 0.5 to be at the center of the pixel, if I add that no more problem.

**Pull request merged**
