### PR TITLE
CMAA_2.fx SimpleBlend LUT textures optimization.

### PR DESCRIPTION
**Pull request by jfouquart**
Reducing the SimpleBlend LUT textures size.

### CODE REVIEW

**Comment by LordOfLunacy** [comment]
Nice, you got that down to a much more reasonable size. Was there a performance increase from this?

**Comment by jfouquart** [comment]
From what I've observed, no :(

**Comment by LordOfLunacy** [comment]
Well from what I understand your GPU is rather old, could be newer archs with their larger caches could benefit more from it. Regardless it's good to have the LUT be smaller, thank you for the improvement.

**Comment by jfouquart** [comment]
You're welcome.

PS: my GPU is an Geforce 9600M GT, pretty old isn't it :).

**Pull request merged**
